name: Vercel Webhook Trigger
on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
    branches:
      - 'production'
      - 'staging'
      - 'upgrade'
jobs:
  promote:
    runs-on: ubuntu-latest
    if: ${{ github.ref_name == 'production' }}
    environment: ${{ github.ref_name }}
    steps:
      - name: Promote to Production
        run: npm install -g vercel && vercel promote $VERCEL_DEPLOYMENT_URL --yes --token=$VERCEL_TOKEN --scope=experius
        env:
          VERCEL_DEPLOYMENT_URL: ${{ github.event.client_payload.url }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  generate-csp-headers:
    runs-on: ubuntu-latest
    needs: promote
    if: ${{ always() && (needs.promote.result == 'success' || needs.promote.result == 'skipped') }}
    steps:
      - name: Generate CSP Headers
        run: |
          npm install -g vercel
          vercel env pull .env.vercel --yes --environment=${VERCEL_ENV} --token=$VERCEL_TOKEN || vercel env pull .env.vercel --yes --environment=preview --token=$VERCEL_TOKEN
          source .env.vercel
          url="https://trigger.happyhorizon.dev/csp_manage_fastly_header?FASTLY_SERVICE_ID=${FASTLY_SERVICE_ID}&FASTLY_API_KEY=${FASTLY_API_KEY}&SANSEC_ID=${SANSEC_ID}&CSP_STRICT=${CSP_STRICT}"
          response=$(curl -sw "%{http_code}" $url)
          status_code="${response:${#response}-3}"
          body=""
          if [ ${#response} -gt 3 ]; then body="${response:0:${#response}-3}"; else body=""; fi
          if [[ "$status_code" -ne 200 ]]; then echo "$body"; pkill LT; fi
        env:
          VERCEL_ENV: ${{ github.ref_name == 'production' && 'production' || 'preview' }}
          VERCEL_PROJECT_ID: ${{ github.event.client_payload.project.id }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  full-purge-fastly:
    runs-on: ubuntu-latest
    needs: [promote, generate-csp-headers]
    if: ${{ always() && (needs.generate-csp-headers.result == 'success' || needs.generate-csp-headers.result == 'skipped') }}
    steps:
      - name: Full Purge Fastly
        run: |
          npm install -g vercel
          vercel env pull .env.vercel --yes --environment=${VERCEL_ENV} --token=$VERCEL_TOKEN || vercel env pull .env.vercel --yes --environment=preview --token=$VERCEL_TOKEN
          source .env.vercel
          url="https://trigger.happyhorizon.dev/fastly-flush-cache?FASTLY_SERVICE_ID=${FASTLY_SERVICE_ID}&FASTLY_API_KEY=${FASTLY_API_KEY}"
          response=$(curl -sw "%{http_code}" $url)
          status_code="${response:${#response}-3}"
          body=""
          if [ ${#response} -gt 3 ]; then body="${response:0:${#response}-3}"; else body=""; fi
          if [[ "$status_code" -ne 200 ]]; then echo "$body"; pkill LT; fi
        env:
          VERCEL_ENV: ${{ github.ref_name == 'production' && 'production' || 'preview' }}
          VERCEL_PROJECT_ID: ${{ github.event.client_payload.project.id }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
