name: Vercel Webhook Trigger
on:
  repository_dispatch:
    types:
      - 'vercel.deployment.success'
    branches:
      - 'production'
      - 'staging'
      - 'upgrade'
jobs:
  vercel:
    uses: happy-horizon/actions/.github/workflows/horizon-storefront-vercel-deployment-success.yml@production
    secrets: inherit
